# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  discoiSCSI = '.vagrant/discoiSCSI.vdi'

  config.vm.define :servidor do |servidor|
    servidor.vm.box = "debian/buster64"
    servidor.vm.hostname = "servidor"
    servidor.vm.network :public_network, :bridge=>"wlo1"
    servidor.vm.provider :virtualbox do |v|
      v.customize ["createhd", "--filename", discoiSCSI, "--size", 1024]
      v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", discoiSCSI]
    end
  end

  config.vm.define :clientelinux do |clientelinux|
    clientelinux.vm.box = "debian/buster64"
    clientelinux.vm.hostname = "clientelinux"
    clientelinux.vm.network :public_network, :bridge=>"wlo1"
  end
end
